name: flutter_application_2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences: ^2.5.3
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  pretty_dio_logger: ^1.4.0
  dio: ^5.9.0
  go_router: ^16.3.0
  flutter_native_splash: ^2.4.7
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  permission_handler: ^12.0.1
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  build_runner: ^2.10.1
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/core/assets/images/fire_icon.png
    - lib/core/assets/images/android12splash.png

flutter_native_splash:
  android: true
  ios: true
  image: lib/core/assets/images/fire_icon.png
  color: "#FFFFFF"

  android_12:
    color: "#FFFFFF"
    image: lib/core/assets/images/Android12.png
    icon_background_color: "#FFFFFF"
